definitions:
  auth.SingUpResp:
    properties:
      token:
        description: token for authorization
        type: string
    type: object
  links.Link:
    properties:
      date:
        type: string
      link:
        type: string
      page:
        type: string
      uuid:
        type: string
    type: object
  stat.Bot:
    properties:
      date:
        type: string
      details:
        items:
          $ref: '#/definitions/stat.Entry'
        type: array
      total:
        type: integer
    type: object
  stat.BrowserCount:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
  stat.DateCountPair:
    properties:
      count:
        type: integer
      date:
        type: string
    type: object
  stat.Entry:
    properties:
      count:
        description: value
        type: integer
      name:
        description: key
        type: string
    type: object
  stat.NameCountPair:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
  stat.SessionResponse:
    properties:
      session:
        type: string
    type: object
  stat.SiteStats:
    properties:
      avg_duration:
        type: integer
      first_visits:
        type: integer
      top_browsers:
        items:
          $ref: '#/definitions/stat.BrowserCount'
        type: array
      top_countries:
        description: Top countries
        items:
          $ref: '#/definitions/stat.NameCountPair'
        type: array
      top_os:
        items:
          $ref: '#/definitions/stat.NameCountPair'
        type: array
      top_pages:
        items:
          $ref: '#/definitions/stat.URLCountPair'
        type: array
      total_bots:
        type: integer
      total_visits:
        type: integer
      total_visits_bot:
        description: Total bots visit by days
        items:
          $ref: '#/definitions/stat.Bot'
        type: array
      visits_by_day:
        items:
          $ref: '#/definitions/stat.DateCountPair'
        type: array
      visits_by_hour:
        items:
          $ref: '#/definitions/stat.TimeCountPair'
        type: array
    type: object
  stat.TimeCountPair:
    properties:
      count:
        type: integer
      time:
        type: string
    type: object
  stat.URLCountPair:
    properties:
      count:
        type: integer
      title:
        type: string
      url:
        type: string
    type: object
  stat.VisitsResponse:
    properties:
      data:
        $ref: '#/definitions/stat.SiteStats'
    type: object
info:
  contact: {}
paths:
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Log in to the admin panel, get a token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SingUpResp'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      tags:
      - Auth
  /api/links/to:
    get:
      description: Link redirect ( for stat )
      parameters:
      - description: the link to which the redirect will be made
        in: query
        name: link
        required: true
        type: string
      - description: the page from which the link was clicked
        in: query
        name: page
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - Links
  /api/stat/links:
    get:
      consumes:
      - application/json
      description: Get links statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/links.Link'
            type: array
      tags:
      - Stat
  /api/stat/update/visit:
    put:
      consumes:
      - application/json
      description: add a visit to the site, gets the IP, country, time of entry and
        uniqueness of the visit
      parameters:
      - description: Unique visit or not (0 - not unique, 1 - unique)
        in: query
        name: un
        required: true
        type: integer
      - description: UTM tag ID (optional parameter)
        in: query
        name: utm
        type: string
      - description: URL Page
        in: query
        name: url
        type: string
      - description: Title Page
        in: query
        name: title
        type: string
      - description: Session (if user yet visited website)
        in: query
        name: session
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful registration of the session and return of the session
            ID
          schema:
            $ref: '#/definitions/stat.SessionResponse'
        "400":
          description: Bad Request
      tags:
      - Stat
  /api/stat/updatevisit/extend:
    put:
      consumes:
      - application/json
      description: Extends the time spent on the site by session ID
      parameters:
      - description: Session ID
        in: query
        name: session
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Stat
  /api/stat/visits:
    get:
      consumes:
      - application/json
      description: Get information about site visits, including the number of visits,
        unique visits, top countries, top browsers and top OS
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stat.VisitsResponse'
      tags:
      - Stat
swagger: "2.0"
